# Generated by Django 3.0.6 on 2020-05-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('imagefile', models.FileField(upload_to='uploads')),
                ('reg_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
